project:
  type: website

website:
  title: "Decoding Chaos"
  page-navigation: true
  back-to-top-navigation: true
  sidebar: false
  navbar:
    logo: "images/Nav_Logo4.png"
    title: false
    right:
      - text: "Home"
        href: "home.html"
      - text: "Shiny App"
        href: ".html"
      - text: "User Guide"
        href: "UserGuide/UserGuide.html"
      - text: "Project Proposal"
        href: "ProjectProposal/ProjectProposal.html"
      - text: "Prototype"
        href: "Prototype/Prototype.html"
  page-footer:
    right: 
      - text: "Â©2024!"

format:
  html:
    theme:
      - flatly
    mermaid: 
      theme: neutral
    css: styles.css
    grid:
      sidebar-width: 100px
      body-width: 1200px
      margin-width: 200px
      gutter-width: 2.0rem
editor: visual